ctbcap-healthcheck: fix not work

diff --git a/ctbcap-healthcheck b/ctbcap-healthcheck
--- a/ctbcap-healthcheck
+++ b/ctbcap-healthcheck
@@ -3,8 +3,10 @@
 # Copyright (C) 2019-2024 KFERMercer <https://github.com/KFERMercer>
 #
 
+[[ ${DEBUG_MODE}  == "1" ]] && set -x # Debug Mode
+
 # Check for assignment of runtime variables
-[ ! ${MODEL} ] || [ ! ${PLATFORM} ] || [ ! ${SAVE_PATH} ] || [ ! ${LOG_PATH} ] && echo "Incomplete Runtime Variables!" && exit 1
+[ ! ${MODEL} ] || [ ! ${PLATFORM} ] || [ ! ${SAVE_PATH} ] || [ ! ${LOG_PATH} ] && echo "(ERROR) Incomplete Runtime Variables!" && exit 1
 
 # Process ${MODEL}
 # Assume ${MODEL} contain some link form, process & cut invalid chars.
@@ -32,18 +34,21 @@ case ${PLATFORM} in
 esac
 
 # Is directories writable?
-[ ! -w ${SAVE_PATH} ] && echo "SAVE_PATH are unwritable!" && exit 1
-[ ! -w ${LOG_PATH} ] && echo "LOG_PATH are unwritable!" && exit 1
+[ ! -w ${SAVE_PATH} ] && echo "(ERROR) SAVE_PATH are unwritable!" && exit 1
+[ ! -w ${LOG_PATH} ] && echo "(ERROR) LOG_PATH are unwritable!" && exit 1
 
 # Flag of ffmpeg process
-FFMPEG_PROCESS=$(ps -ef | grep -oE "[f]fmpeg -i.*${MODEL}.*\.m3u8*" 2>/dev/null)
+FFMPEG_PROCESS=$(ps -ef | grep -oE "[f]fmpeg.*-i.*.m3u8.*${MODEL_NAME}.*.mkv" 2>/dev/null)
 # No ffmpeg process --> normal
 [ ! "${FFMPEG_PROCESS}" ] && exit 0
 
 # If Model currently online, set HTTP Status Code of m3u8 link as flag
-[ -f ${LOG_PATH}/${MODEL}.online ] && M3U8_RESPONSE=$(curl $(cat ${LOG_PATH}/${PLATFORM}-${MODEL}.online) -4 -s -I -w %{http_code} -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' 2>/dev/null | tail -n1)
+if [ -f ${LOG_PATH}/${MODEL_NAME}-${PLATFORM}.online ]; then
+    # Has ffmpeg process, but m3u8 link are unavailable --> err
+    M3U8_RESPONSE=$(curl $(cat ${LOG_PATH}/${MODEL_NAME}-${PLATFORM}.online) -4 -L -s -H "user-agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'" --compressed --retry 3 --retry-delay 2 2>/dev/null | tr -d '\r')
 
-# Has ffmpeg process, but m3u8 link are unavailable --> err
-[ "${FFMPEG_PROCESS}" ] && [ ${M3U8_RESPONSE} -ge 400 ] && echo "(ERROR) FFMPEG process did not exit correctly!" && exit 1
+    [[ ! ${FFMPEG_PROCESS} ]] && echo "(ERROR) FFMPEG process did not exit correctly!" && exit 1
+fi
 
+echo "Everything is OK!"
 exit 0
