ctbcap: replace conjunction chain with code block

diff --git a/ctbcap-healthcheck b/ctbcap-healthcheck
--- a/ctbcap-healthcheck
+++ b/ctbcap-healthcheck
@@ -20,7 +20,7 @@ _MODEL="$(echo "${MODEL}" \
 [ -n "${_MODEL}" ] && MODEL="${_MODEL}"
 # If ${MODEL} not URL form, cut invalid chars.
 [ -z "${_MODEL}" ] && _MODEL="$(echo "${MODEL}" | tr '[:upper:]' '[:lower:]'| grep -oE '[a-z0-9_-]+' | head -n 1)"
-[ -z "${_MODEL}" ] && echo "(ERROR) Invalid Username or Link!" && exit 1
+[ -z "${_MODEL}" ] && { echo "(ERROR) Invalid Username or Link!"; exit 1; }
 [ -n "${_MODEL}" ] && MODEL="${_MODEL}"
 
 # Process $PLATFORM
@@ -33,23 +33,24 @@ stripchat|stc|sc|st)
     PLATFORM=stripchat
 ;;
 *)
-    echo "(ERROR) Invalid Platform!" && exit 1
+    echo "(ERROR) Invalid Platform!"
+    exit 1
 ;;
 esac
 
 # Is directories writable?
-[ ! -w "${SAVE_PATH}" ] && echo "(ERROR) SAVE_PATH is unwritable!" && exit 1
-[ ! -w "${LOG_PATH}" ] && echo "(ERROR) LOG_PATH is unwritable!" && exit 1
+[ ! -w "${SAVE_PATH}" ] && { echo "(ERROR) SAVE_PATH is unwritable!"; exit 1; }
+[ ! -w "${LOG_PATH}" ] && { echo "(ERROR) LOG_PATH is unwritable!"; exit 1; }
 
 # If Model currently online, set HTTP Status Code of m3u8 link as flag
 [ -f "${LOG_PATH}/${MODEL}-${PLATFORM}.online" ] && {
     STREAM_LINK="$(cat "${LOG_PATH}/${MODEL}-${PLATFORM}.online")"
     UA="$(ctbcap -v | grep '^UA: ' | sed 's|UA: ||')"
-    [ -z "${UA}" ] && echo "(ERROR) UA does not exist!" && exit 1
+    [ -z "${UA}" ] && { echo "(ERROR) UA does not exist!"; exit 1; }
     # Has ffmpeg process, but m3u8 link is unavailable --> err
     FFMPEG_PROCESS=$(ps -ef | grep -oE "[f]fmpeg.*-i.*.m3u8.*${MODEL}.*.mkv" 2>/dev/null)
     M3U8_RESPONSE=$(curl "${STREAM_LINK}" -4 -L -s -A "${UA}" --compressed --retry 3 --retry-delay 2 2>/dev/null | tr -d '\r')
-    [ -n "${FFMPEG_PROCESS}" ] && [ -z "${M3U8_RESPONSE}" ] && echo "(ERROR) FFMPEG process did not exit correctly!" && exit 1
+    [ -n "${FFMPEG_PROCESS}" ] && [ -z "${M3U8_RESPONSE}" ] && { echo "(ERROR) FFMPEG process did not exit correctly!"; exit 1; }
 }
 
 echo "Everything is OK!"
