ctbcap: chaturbate: bring back old backend spt
link to: https://github.com/KFERMercer/chaturbate-grabber/discussions/29

diff --git a/ctbcap b/ctbcap
--- a/ctbcap
+++ b/ctbcap
@@ -427,12 +427,15 @@ fetch_m3u() {
 		2*|3*)
 			local ROOM_STATUS="$(echo "${CONNECT_DUMP}" | grep -oE '"room_status":[ ]?"[^"]+"' | head -n 1 | cut -d '"' -f4)"
 			[ -n "$(echo "${CONNECT_DUMP}" | grep -oE 'http[s]?://edge[^ ]+\.m3u8'| head -n 1)" ] && {
-				STREAM_URL=$(echo "${CONNECT_DUMP}" \
-						| grep -oE 'http[s]?://edge[^ ]+\.m3u8' \
-						| head -n 1 \
-						| sed 's|playlist.m3u8|playlist_sfm4s.m3u8|g' \
-						| sed 's|live-hls|live-c-fhls|g'
-					)
+				STREAM_URL=$(echo "${CONNECT_DUMP}" | grep -oE 'http[s]?://edge[^ ]+\.m3u8' | head -n 1)
+				[ "$(utils connect_status "${STREAM_URL}")" -ge 400 ] && {
+					STREAM_URL=$(echo "${STREAM_URL}" | sed 's|playlist.m3u8|playlist_sfm4s.m3u8|g' | sed 's|live-hls|live-c-fhls|g')
+					[ "$(utils connect_status "${STREAM_URL}")" -ge 400 ] && {
+						unset STREAM_URL
+						echo "[$(date "+%Y%m%d-%H%M%S")] (ERROR) [${MODEL}] is Online now, but looks like the backend of [${PLATFORM}] has been changed." >&2
+						return 1
+					}
+				}
 				true
 			} || {
 				echo "[$(date "+%Y%m%d-%H%M%S")] [${MODEL}] is ${ROOM_STATUS} now. [${CONNECT_STATUS}]"
