ctbcap: fallback to sh to compliant POSIX standard - drop bash require

diff --git a/ctbcap b/ctbcap
--- a/ctbcap
+++ b/ctbcap
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
 #
 # Copyright (C) 2019-2024 KFERMercer <https://github.com/KFERMercer>
 #
@@ -9,36 +9,36 @@ CTBCAP_VERSION=2.0
 CTBCAP_RELEASE=6
 
 # Streams saving path
-[[ ${SAVE_PATH} ]] || SAVE_PATH="${PWD}/cap"
+[ -n "${SAVE_PATH}" ] || SAVE_PATH="${PWD}/cap"
 
 # Logs saving path
-[[ ${LOG_PATH} ]] || LOG_PATH="${SAVE_PATH}/log/"
+[ -n "${LOG_PATH}" ] || LOG_PATH="${SAVE_PATH}/log/"
 
 # Streamer's Username or Room Link
-[[ ${MODEL} ]] || MODEL=
+[ -n "${MODEL}" ] || MODEL=
 
 # Platform that streaming at. Choose <chaturbate> (default) or <stripchat>.
-[[ ${PLATFORM} ]] || PLATFORM="chaturbate"
+[ -n "${PLATFORM}" ] || PLATFORM="chaturbate"
 
 # Edging Mode.
 # Delay initial requests to servers to avoid time-specific request waves caused by large-scale deployments.
 # Inactive if not 1.
-[[ ${EDGING_MODE} ]] || EDGING_MODE="uncle makes me pee white"
+[ -n "${EDGING_MODE}" ] || EDGING_MODE="uncle makes me pee white"
 
 # Debug Mode. Inactive if not 1.
-[[ ${DEBUG_MODE} ]] || DEBUG_MODE="your mom is so hot"
+[ -n "${DEBUG_MODE}" ] || DEBUG_MODE="your mom is so hot"
 
 # Stream Mode. Only grab stream link. Inactive if not 1.
-[[ ${STREAM_MODE} ]] || STREAM_MODE=
+[ -n "${STREAM_MODE}" ] || STREAM_MODE=
 
 # https://jnrbsn.github.io/user-agents/user-agents.json
-[[ ${UA} ]] || UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'
+[ -n "${UA}" ] || UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'
 
 
 # Check validity and process runtime variables.
-function prepare_simping() {
+prepare_simping() {
 
-	[ $# -gt 2 ] && echo -e "(ERROR) Invalid Parameter Number! \n" >&2 && exit 1
+	[ $# -gt 2 ] && printf "(ERROR) Invalid Parameter Number! \n\n" >&2 && exit 1
 
 	case $1 in
 		-h|--help)
@@ -51,8 +51,8 @@ function prepare_simping() {
 			exit 0
 		;;
 		-s|--stream)
-			[[ ! $2 ]] \
-				&& echo -e "(ERROR) Must contain <username or url> as \$2 ! \nSee --help for more \n" >&2 \
+			[ -z $2 ] \
+				&& printf "(ERROR) Must contain <username or url> as \$2 ! \nSee --help for more \n\n" >&2 \
 				&& exit 1
 
 			STREAM_MODE=1
@@ -67,12 +67,12 @@ function prepare_simping() {
 			exit 0
 		;;
 		-*|--*)
-			echo -e "(ERROR) Invalid Parameter [$1] ! \n" >&2
+			printf "(ERROR) Invalid Parameter [$1] ! \n\n" >&2
 			exit 1
 		;;
 		'')
-			[[ ! ${MODEL} ]] \
-				&& echo -e "(ERROR) Need Parameter! See --help \n" >&2 \
+			[ -z "${MODEL}" ] \
+				&& printf "(ERROR) Need Parameter! See --help \n\n" >&2 \
 				&& exit 1
 		;;
 		*)
@@ -82,40 +82,41 @@ function prepare_simping() {
 
 	case $2 in
 		-*|--*)
-			echo -e "(ERROR) Invalid Parameter [$2] ! \n" >&2
+			printf "(ERROR) Invalid Parameter [$2] ! \n\n" >&2
 			exit 1
 		;;
 		'')
 		;;
 		*)
 			[ ! $1 = '-s' ] && [ ! $1 = '--stream' ] \
-				&& echo -e "(ERROR) Invalid Parameter [$2] ! \n" >&2 \
+				&& printf "(ERROR) Invalid Parameter [$2] ! \n\n" >&2 \
 				&& exit 1
 
-			[[ ${MODEL} ]] || MODEL=$2
+			[ -n "${MODEL}" ] || MODEL=$2
 		;;
 	esac
 
 	# Assume ${MODEL} contain some link form, process & cut invalid chars.
-	local MODEL_TEMP=$(echo ${MODEL,,} \
+	local MODEL_TEMP=$(echo ${MODEL} \
+		| tr '[:upper:]' '[:lower:]' \
 		| grep -oE 'http[s]?://[a-zA-Z]?+[.]?[a-zA-Z]+[.][a-zA-Z]+[/][^ /]+' \
 		| cut -d '/' -f4 \
 		| grep -oE '[a-zA-Z0-9_-]+' \
 		| head -n 1)
-	[[ ${MODEL_TEMP} ]] && MODEL=${MODEL_TEMP}
+	[ -n "${MODEL_TEMP}" ] && MODEL=${MODEL_TEMP}
 	# If ${MODEL} not link form, cut invalid chars.
-	[[ ! ${MODEL_TEMP} ]] && MODEL=$(echo "${MODEL,,}" | grep -oE '[a-zA-Z0-9_-]+' | head -n 1)
-	[[ ! ${MODEL} ]] && echo -e "(ERROR) Invalid Username or Link! [${MODEL}]\n" >&2 && exit 1
+	[ -z "${MODEL_TEMP}" ] && MODEL=$(echo ${MODEL} | tr '[:upper:]' '[:lower:]'| grep -oE '[a-zA-Z0-9_-]+' | head -n 1)
+	[ -z "${MODEL}" ] && printf "(ERROR) Invalid Username or Link! [${MODEL}]\n\n" >&2 && exit 1
 
 	SAVE_PATH=${SAVE_PATH%"/"}
 	LOG_PATH=${LOG_PATH%"/"}
-	if [[ ${STREAM_MODE} != "1" ]]; then
+	if [ "${STREAM_MODE}" != "1" ]; then
 		mkdir -p ${LOG_PATH} ${SAVE_PATH} 2>/dev/null
-		[ ! -w ${SAVE_PATH} ] && echo -e "(ERROR) Cannot Access To [${SAVE_PATH}/] ! \n" >&2 && exit 1
-		[ ! -w ${LOG_PATH} ] && echo -e "(ERROR) Cannot Access To [${LOG_PATH}/] ! \n" >&2 && exit 1
+		[ ! -w ${SAVE_PATH} ] && printf "(ERROR) Cannot Access To [${SAVE_PATH}/] ! \n\n" >&2 && exit 1
+		[ ! -w ${LOG_PATH} ] && printf "(ERROR) Cannot Access To [${LOG_PATH}/] ! \n\n" >&2 && exit 1
 	fi
 
-	PLATFORM=${PLATFORM,,}
+	PLATFORM=$(echo ${PLATFORM} | tr '[:upper:]' '[:lower:]')
 	case ${PLATFORM} in
 		chaturbate|ctb|cb)
 			PLATFORM=chaturbate
@@ -126,7 +127,7 @@ function prepare_simping() {
 			LINK="https://stripchat.com/api/front/v2/models/username/${MODEL}/cam"
 		;;
 		*)
-			echo -e "(ERROR) Unknown Platform: [${PLATFORM}] ! \n" >&2 && exit 1
+			printf "(ERROR) Unknown Platform: [${PLATFORM}] ! \n\n" >&2 && exit 1
 		;;
 	esac
 
@@ -135,7 +136,7 @@ function prepare_simping() {
 
 }
 
-function edging () {
+edging () {
 
 	# Sleep time (s) before initial request to server. Range better EQ to ..watchdog().while.else.echo .
 	[ $1 ] && local EDGING_TIME=$1 || local EDGING_TIME=$((RANDOM % 600)) # Random num B/E 0 - 600 (10 min)
@@ -155,13 +156,13 @@ function edging () {
 
 }
 
-function connect_utils() {
+connect_utils() {
 
 	case $1 in
 		status)
 			curl $2 \
 			-4 -L -s -I \
-			-H "user-agent: ${UA}" \
+			-A "${UA}" \
 			--compressed \
 			--connect-timeout 5 --retry 5 --retry-delay 2 \
 			2>/dev/null | head -n 1 | grep -oE '[0-9]{3}' \
@@ -170,7 +171,7 @@ function connect_utils() {
 		dump)
 			curl $2 \
 			-4 -L -s -i\
-			-H "user-agent: ${UA}" \
+			-A "${UA}" \
 			--compressed \
 			--connect-timeout 5 --retry 5 --retry-delay 2 \
 			2>/dev/null | tr -d '\r'
@@ -181,23 +182,23 @@ function connect_utils() {
 
 # Fetch ${STREAM_LINK_GENERIC} & ${STREAM_LINK}, show them & return 0.
 # If dont have ${STREAM_LINK_GENERIC} & ${STREAM_LINK}, return 1.
-function fetch_m3u() {
+fetch_m3u() {
 
 	rm -f ${LOG_PATH}/${MODEL}-${PLATFORM}.online
 	unset STREAM_LINK_GENERIC STREAM_LINK
 
-	[ ! ${MODEL_NEW_NAME} ] && local CONNECT_DUMP=$(connect_utils dump ${LINK})
-	[ ${MODEL_NEW_NAME} ] && local CONNECT_DUMP=$(connect_utils dump ${LINK_NEW_NAME})
+	[ -z "${MODEL_NEW_NAME}" ] && local CONNECT_DUMP=$(connect_utils dump ${LINK})
+	[ -n "${MODEL_NEW_NAME}" ] && local CONNECT_DUMP=$(connect_utils dump ${LINK_NEW_NAME})
 	# Reuse ${CONNECT_DUMP} to get HTTP status code at the time.
-	local CONNECT_STATUS=$(echo ${CONNECT_DUMP:0:15} | grep -oE '[0-9]{3}' || echo 000)
+	local CONNECT_STATUS=$(echo ${CONNECT_DUMP} | cut -c -15 | grep -oE '[0-9]{3}' || echo 000)
 	case ${CONNECT_STATUS} in
 	2*|3*)
 		# Do nothing. leave to platform method to deal with.
 	;;
 	404)
 		# ↓↓↓ Only effects on Stream Mode. Of not this mode, will leave to platform method to handle.
-		[[ ${STREAM_MODE} == "1" ]] \
-			&& echo -e "(ERROR) Can't find [${MODEL}] on [${PLATFORM}]. [${CONNECT_STATUS}] \n" >&2 \
+		[ "${STREAM_MODE}" = "1" ] \
+			&& printf "(ERROR) Can't find [${MODEL}] on [${PLATFORM}]. [${CONNECT_STATUS}] \n\n" >&2 \
 			&& exit 1
 	;;
 	4*)
@@ -206,12 +207,12 @@ function fetch_m3u() {
 	;;
 	000)
 		echo "[$(date "+%Y%m%d-%H%M%S")] Internet Connection Error. [${CONNECT_STATUS}]" >&2
-		[[ ${STREAM_MODE} == "1" ]] && echo >&2 && exit 1
+		[ "${STREAM_MODE}" = "1" ] && echo >&2 && exit 1
 		return 1
 	;;
 	1*|5*|*)
 		echo "[$(date "+%Y%m%d-%H%M%S")] ${PLATFORM} Server on failure now. [${CONNECT_STATUS}]" >&2
-		[[ ${STREAM_MODE} == "1" ]] && echo >&2 && exit 1
+		[ "${STREAM_MODE}" = "1" ] && echo >&2 && exit 1
 		return 1
 	;;
 	esac
@@ -221,26 +222,27 @@ function fetch_m3u() {
 		# Cheke of Model change to new name
 		if [ ${CONNECT_STATUS} -eq 404 ]; then
 			MODEL_NEW_NAME=$(connect_utils dump "https://chaturbate.com/${MODEL}/")
-			local CONNECT_STATUS=$(echo ${MODEL_NEW_NAME:0:15} | grep -oE '[0-9]{3}' || echo 000)
+			local CONNECT_STATUS=$(echo ${MODEL_NEW_NAME} | cut -c -15 | grep -oE '[0-9]{3}' || echo 000)
 			MODEL_NEW_NAME=$(echo ${MODEL_NEW_NAME} | grep -oE 'location:[ ]?/[^/]+/' | head -n 1 | cut -d '/' -f2)
 			LINK_NEW_NAME=$(echo ${LINK} | sed "s|${MODEL}|${MODEL_NEW_NAME}|g")
-			[ ${MODEL_NEW_NAME} ] \
+			[ -n "${MODEL_NEW_NAME}" ] \
 				&& echo "[$(date "+%Y%m%d-%H%M%S")] (WARNING) [${MODEL}] has changed her name to [${MODEL_NEW_NAME}]. [${CONNECT_STATUS}]" >&2 \
 				&& sleep 5 \
 				&& local CONNECT_DUMP=$(connect_utils dump ${LINK_NEW_NAME}) \
-				&& local CONNECT_STATUS=$(echo ${CONNECT_DUMP:0:15} | grep -oE '[0-9]{3}' || echo 000)
-			[ ! ${MODEL_NEW_NAME} ] && \
-				echo -e "(ERROR) Can't find [${MODEL}] on [${PLATFORM}]. [${CONNECT_STATUS}] \n" >&2 && exit 1
+				&& local CONNECT_STATUS=$(echo ${CONNECT_DUMP} | cut -c -15 | grep -oE '[0-9]{3}' || echo 000)
+			[ -z "${MODEL_NEW_NAME}" ] && \
+				printf "(ERROR) Can't find [${MODEL}] on [${PLATFORM}]. [${CONNECT_STATUS}] \n\n" >&2 && exit 1
 		else
-			[ ${MODEL_NEW_NAME} ] \
+			[ -n "${MODEL_NEW_NAME}" ] \
 				&& echo "[$(date "+%Y%m%d-%H%M%S")] (WARNING) [${MODEL}] has changed her name to [${MODEL_NEW_NAME}]." >&2
 		fi
 
-		if [[ ${CONNECT_DUMP} =~ ".m3u8" ]]; then
-			STREAM_LINK_GENERIC=$(echo -e ${CONNECT_DUMP} | grep -oE 'http[s]?://edge[^ ]+\.m3u8' | head -n 1)
+		local ROOM_STATUS=$(echo ${CONNECT_DUMP} | grep -oE '"room_status":[ ]?"[^"]+"' | cut -d '"' -f4)
+
+		STREAM_LINK_GENERIC=$(echo ${CONNECT_DUMP} | grep -oE 'http[s]?://edge[^ ]+\.m3u8' | head -n 1)
+		if [ -n "${STREAM_LINK_GENERIC}" ]; then
 			STREAM_LINK=$(connect_utils dump ${STREAM_LINK_GENERIC} | tail -n 1)
-			local ROOM_STATUS=$(echo ${CONNECT_DUMP} | grep -oE '"room_status":[ ]?"[^"]+"' | cut -d '"' -f4)
-			[[ ${STREAM_LINK} ]] && STREAM_LINK=${STREAM_LINK_GENERIC%%playlist.m3u8*}${STREAM_LINK}
+			[ -n "${STREAM_LINK}" ] && STREAM_LINK=$(echo ${STREAM_LINK_GENERIC} | sed 's|playlist.m3u8.*||')${STREAM_LINK}
 		else
 			echo "[$(date "+%Y%m%d-%H%M%S")] [${MODEL}] is ${ROOM_STATUS} now. [${CONNECT_STATUS}]"
 			return 1
@@ -249,13 +251,13 @@ function fetch_m3u() {
 	stripchat)
 		if [ ${CONNECT_STATUS} -eq 404 ]; then
 			# TODO: Name changing detection for Stripchat method.
-			echo -e "(ERROR) Can't find [${MODEL}] on [${PLATFORM}]. [${CONNECT_STATUS}] \n" >&2 && exit 1
+			echo -e "(ERROR) Can't find [${MODEL}] on [${PLATFORM}]. [${CONNECT_STATUS}] \n\n" >&2 && exit 1
 		fi
 
-		if [[ ${CONNECT_DUMP} =~ '"isCamAvailable":true' ]]; then
+		if [ "${CONNECT_DUMP}" = *'"isCamAvailable":true'* ]; then
 			local STREAMNAME=$(echo -e ${CONNECT_DUMP})
-			local STREAMNAME=${STREAMNAME#*'"streamName":"'}
-			local STREAMNAME=${STREAMNAME%%'"'*}
+			local STREAMNAME=$(${STREAMNAME} | sed 's|.*"streamName":"||')
+			local STREAMNAME=$(echo ${STREAMNAME} | sed 's|".*||')
 			STREAM_LINK_GENERIC="https://edge-hls.doppiocdn.com/hls/${STREAMNAME}/master/${STREAMNAME}_auto.m3u8"
 			STREAM_LINK=$(connect_utils dump ${STREAM_LINK_GENERIC} | grep -oE 'http[s]?://[^ ]+\.m3u8' | head -n 1)
 		else
@@ -266,12 +268,13 @@ function fetch_m3u() {
 	esac
 
 	# If successfully grabed ${STREAM_LINK_GENERIC} ${STREAM_LINK}, show them.
-	if [ ${STREAM_LINK} ]; then
-		echo "[$(date "+%Y%m%d-%H%M%S")] Captured Stream Link with status [$([ ${ROOM_STATUS} ] && echo ${ROOM_STATUS} || echo online)] :"
+	if [ -n "${STREAM_LINK}" ]; then
+		echo "[$(date "+%Y%m%d-%H%M%S")] [${MODEL}] is Online now! [$([ -n "${ROOM_STATUS}" ] && echo ${ROOM_STATUS} || echo online)]"
+		echo "[$(date "+%Y%m%d-%H%M%S")] Successfully Captured Stream Link:"
 		echo "[$(date "+%Y%m%d-%H%M%S")] ${STREAM_LINK_GENERIC}"
 		echo "[$(date "+%Y%m%d-%H%M%S")] Highest Definition Stream Link:"
 		echo "[$(date "+%Y%m%d-%H%M%S")] ${STREAM_LINK}"
-		[[ ${STREAM_MODE} == "1" ]] && echo
+		[ "${STREAM_MODE}" = "1" ] && echo
 		return 0
 	else
 		echo "[$(date "+%Y%m%d-%H%M%S")] Failed to fetch stream link! [$(connect_utils status ${STREAM_LINK_GENERIC})]"
@@ -279,7 +282,7 @@ function fetch_m3u() {
 
 }
 
-function grab_stream() {
+grab_stream() {
 
 	local FFMPEG_LOGFILE="${LOG_PATH}/${MODEL}-${PLATFORM}.ffmpeg.log"
 	local CAPTURE_TIME=$(date "+%Y%m%d-%H%M%S")
@@ -301,13 +304,14 @@ function grab_stream() {
 	>> ${FFMPEG_LOGFILE} 2>&1
 }
 
-function watchdog() {
+watchdog() {
 	while true; do
 		fetch_m3u
-		if [ ${STREAM_LINK} ]; then
+		if [ -n "${STREAM_LINK}" ]; then
 
 			echo "[$(date "+%Y%m%d-%H%M%S")] Now start recording..."
 			echo ${STREAM_LINK} > ${LOG_PATH}/${MODEL}-${PLATFORM}.online # Build online flag file
+			echo ${UA} >> ${LOG_PATH}/${MODEL}-${PLATFORM}.online
 
 			grab_stream
 			# If recording interrupt by first time
@@ -338,7 +342,7 @@ function watchdog() {
 	done
 }
 
-function sock_washer() {
+sock_washer() {
 	rm -f ${LOG_PATH}/${MODEL}-${PLATFORM}.online
 	echo
 	echo "BYE (. Y .) BYE"
@@ -348,7 +352,7 @@ function sock_washer() {
 
 # Execution Entry
 
-trap 'sock_washer' SIGHUP SIGINT SIGQUIT SIGTERM
+trap 'sock_washer' HUP INT QUIT TERM
 
 echo
 echo "8=====================================================D"
@@ -362,13 +366,12 @@ echo
 
 prepare_simping $1 $2 $3
 
-[[ ${DEBUG_MODE}  == "1" ]] && set -x # Debug Mode
+[ "${DEBUG_MODE}" = "1" ] && set -x # Debug Mode
 
-[[ ${EDGING_MODE} == "1" ]] && edging
+[ "${EDGING_MODE}" = "1" ] && edging
 
-[[ ${STREAM_MODE} == "1" ]] && fetch_m3u && exit 0
+[ "${STREAM_MODE}" = "1" ] && fetch_m3u && exit 0
 
-watchdog > >(tee -a ${LOG_PATH}/${MODEL}-${PLATFORM}.log >> /dev/stdout) \
-		2> >(tee -a ${LOG_PATH}/${MODEL}-${PLATFORM}.log >> /dev/stderr)
+watchdog | tee -a ${LOG_PATH}/${MODEL}-${PLATFORM}.log
 
 exit 0
diff --git a/ctbcap-healthcheck b/ctbcap-healthcheck
--- a/ctbcap-healthcheck
+++ b/ctbcap-healthcheck
@@ -1,26 +1,28 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
 #
 # Copyright (C) 2019-2024 KFERMercer <https://github.com/KFERMercer>
 #
 
-[[ ${DEBUG_MODE}  == "1" ]] && set -x # Debug Mode
+[ "${DEBUG_MODE}"  = "1" ] && set -x # Debug Mode
 
 # Check for assignment of runtime variables
-[ ! ${MODEL} ] || [ ! ${PLATFORM} ] || [ ! ${SAVE_PATH} ] || [ ! ${LOG_PATH} ] && echo "(ERROR) Incomplete Runtime Variables!" && exit 1
+[ -z "${MODEL}" ] || [ -z "${PLATFORM}" ] || [ -z "${SAVE_PATH}" ] || [ -z "${LOG_PATH}" ] && echo "(ERROR) Incomplete Runtime Variables!" && exit 1
 
 # Process ${MODEL}
 # Assume ${MODEL} contain some link form, process & cut invalid chars.
-MODEL_NAME=$(echo ${MODEL,,} \
+MODEL_TEMP=$(echo ${MODEL} \
+    | tr '[:upper:]' '[:lower:]' \
     | grep -oE 'http[s]?://[a-zA-Z]?+[.]?[a-zA-Z]+[.][a-zA-Z]+[/][^ /]+' \
     | cut -d '/' -f4 \
     | grep -oE '[a-zA-Z0-9_-]+' \
     | head -n 1)
+[ -n "${MODEL_TEMP}" ] && MODEL=${MODEL_TEMP}
 # If ${MODEL} not link form, cut invalid chars.
-[[ ! ${MODEL_NAME} ]] && MODEL_NAME=$(echo "${MODEL,,}" | grep -oE '[a-zA-Z0-9_-]+' | head -n 1)
-[[ ! ${MODEL_NAME} ]] && echo "(ERROR) Invalid Username or Link!" && exit 1
+[ -z "${MODEL_TEMP}" ] && MODEL=$(echo ${MODEL} | tr '[:upper:]' '[:lower:]'| grep -oE '[a-zA-Z0-9_-]+' | head -n 1)
+[ -z "${MODEL}" ] && echo "(ERROR) Invalid Username or Link!" && exit 1
 
 # Process $PLATFORM
-PLATFORM=${PLATFORM,,}
+PLATFORM=$(echo ${PLATFORM} | tr '[:upper:]' '[:lower:]')
 case ${PLATFORM} in 
     chaturbate|ctb|cb)
         PLATFORM=chaturbate
@@ -38,17 +40,17 @@ esac
 [ ! -w ${LOG_PATH} ] && echo "(ERROR) LOG_PATH are unwritable!" && exit 1
 
 # Flag of ffmpeg process
-FFMPEG_PROCESS=$(ps -ef | grep -oE "[f]fmpeg.*-i.*.m3u8.*${MODEL_NAME}.*.mkv" 2>/dev/null)
-# No ffmpeg process --> normal
-[ ! "${FFMPEG_PROCESS}" ] && exit 0
-
+FFMPEG_PROCESS=$(ps -ef | grep -oE "[f]fmpeg.*-i.*.m3u8.*${MODEL}.*.mkv" 2>/dev/null)
 # If Model currently online, set HTTP Status Code of m3u8 link as flag
-if [ -f ${LOG_PATH}/${MODEL_NAME}-${PLATFORM}.online ]; then
+if [ -f ${LOG_PATH}/${MODEL}-${PLATFORM}.online ]; then
+    STREAM_LINK=$(sed -n '1p' ${LOG_PATH}/${MODEL}-${PLATFORM}.online)
+    UA=$(sed -n '2p' ${LOG_PATH}/${MODEL}-${PLATFORM}.online)
     # Has ffmpeg process, but m3u8 link are unavailable --> err
-    M3U8_RESPONSE=$(curl $(cat ${LOG_PATH}/${MODEL_NAME}-${PLATFORM}.online) -4 -L -s -H "user-agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'" --compressed --retry 3 --retry-delay 2 2>/dev/null | tr -d '\r')
+    M3U8_RESPONSE=$(curl ${STREAM_LINK} -4 -L -s -A "${UA}" --compressed --retry 3 --retry-delay 2 2>/dev/null | tr -d '\r')
 
-    [[ ! ${FFMPEG_PROCESS} ]] && echo "(ERROR) FFMPEG process did not exit correctly!" && exit 1
+    [ -z "${FFMPEG_PROCESS}" ] && echo "(ERROR) FFMPEG process did not exit correctly!" && exit 1
 fi
 
 echo "Everything is OK!"
+
 exit 0
