ctbcap-healthcheck: fix $UA check

diff --git a/ctbcap-healthcheck b/ctbcap-healthcheck
--- a/ctbcap-healthcheck
+++ b/ctbcap-healthcheck
@@ -45,7 +45,7 @@ FFMPEG_PROCESS=$(ps -ef | grep -oE "[f]fmpeg.*-i.*.m3u8.*${MODEL}.*.mkv" 2>/dev/
 if [ -f ${LOG_PATH}/${MODEL}-${PLATFORM}.online ]; then
     STREAM_LINK=$(sed -n '1p' ${LOG_PATH}/${MODEL}-${PLATFORM}.online)
     UA=$(sed -n '2p' ${LOG_PATH}/${MODEL}-${PLATFORM}.online)
-    [ -z ${UA} ] && echo "(ERROR) UA does not exist!" && exit 1
+    [ -z "${UA}" ] && echo "(ERROR) UA does not exist!" && exit 1
     # Has ffmpeg process, but m3u8 link are unavailable --> err
     M3U8_RESPONSE=$(curl ${STREAM_LINK} -4 -L -s -A "${UA}" --compressed --retry 3 --retry-delay 2 2>/dev/null | tr -d '\r')
     [ -z "${M3U8_RESPONSE}" ] && echo "(ERROR) FFMPEG process did not exit correctly!" && exit 1
